const User = require('../models/User');
const Counter = require('../models/Counter');
const Enrollment = require('../models/Enrollment');
const TeacherAssignment = require('../models/TeacherAssignment');
const Class = require('../models/Class');
const AcademicYear = require('../models/AcademicYear');

const getNextSequenceValue = async (sequenceName) => {
  const sequenceDocument = await Counter.findOneAndUpdate(
    { id: sequenceName },
    { $inc: { seq: 1 } },
    { new: true, upsert: true }
  );
  return sequenceDocument.seq;
};

exports.registerStudent = async (req, res) => {
  try {
    const { studentId: customStudentId, grNumber: customGrNumber, name, email, password: customPassword, gender, dateOfBirth, contactDetails, classId, isClassLeader } = req.body;
    
    // Authorization check
    if (req.user.role !== 'teacher' && req.user.role !== 'principal') {
      return res.status(403).json({ success: false, message: 'Unauthorized' });
    }

    const cls = await Class.findById(classId);
    if (!cls) return res.status(404).json({ success: false, message: 'Class not found' });

    // Strict class-section permission for Teacher
    if (req.user.role === 'teacher') {
      if (!cls.teacherId || cls.teacherId.toString() !== req.user._id.toString()) {
        return res.status(403).json({ success: false, message: 'Only the designated Class Teacher can add students to this class.' });
      }
    }

    const currentYear = new Date().getFullYear();
    const grSeq = await getNextSequenceValue('grNumber');
    const studentSeq = await getNextSequenceValue(`studentId_${classId}`);
    
    const autoGrNumber = `GR${currentYear}${String(grSeq).padStart(4, '0')}`;
    const autoGeneratedId = `${currentYear}${cls.standard}${cls.section}${String(studentSeq).padStart(2, '0')}`;
    const studentId = customStudentId ? customStudentId : autoGeneratedId;
    const grNumber = customGrNumber ? customGrNumber : autoGrNumber;

    // Explicitly check for duplicate student ID or GR Number
    if (customStudentId) {
      const existing = await User.findOne({ studentId: customStudentId });
      if (existing) {
        return res.status(400).json({ success: false, message: 'An account with that Student ID already exists.' });
      }
    }

    if (customGrNumber) {
      const existingGR = await User.findOne({ grNumber: customGrNumber });
      if (existingGR) {
        return res.status(400).json({ success: false, message: 'An account with that GR Number already exists.' });
      }
    }

    // Create user
    let tempPassword = customPassword;
    if (!tempPassword) {
      const generateSecureTempPassword = require("../utils/generatePassword");
      tempPassword = generateSecureTempPassword();
    }
    const newUser = await User.create({
      name,
      email: email || `${studentId.toLowerCase()}.${grNumber.toLowerCase()}@studymate.school`,
      password: tempPassword,
      mustChangePassword: false,
      role: 'student',
      studentId,
      grNumber,
      gender,
      dateOfBirth,
      contactDetails,
      schoolId: req.user.schoolId
    });

    // Create Enrollment
    const activeYear = await AcademicYear.findOne({ status: 'active' }) || { _id: null };
    await Enrollment.create({
      studentId: newUser._id,
      academicYearId: activeYear._id,
      classId: classId,
      schoolId: req.user.schoolId,
      type: 'new_admission',
      status: 'active'
    });

    // Add to class and optionally set as class leader
    const classUpdate = { $push: { students: newUser._id } };
    if (isClassLeader) {
      classUpdate.$set = { classLeader: newUser._id };
    }
    await Class.findByIdAndUpdate(classId, classUpdate);

    res.status(201).json({
      success: true,
      message: 'Student registered successfully',
      data: {
        studentId: newUser.studentId,
        grNumber: newUser.grNumber,
        tempPassword
      }
    });

  } catch (error) {
    if (error.code === 11000) {
      const field = Object.keys(error.keyValue)[0];
      return res.status(400).json({ success: false, message: `An account with that ${field} already exists.` });
    }
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.getStudents = async (req, res) => {
  try {
    let students = [];
    let classesList = [];
    if (req.user.role === 'principal') {
      students = await User.find({ role: 'student', schoolId: req.user.schoolId }).lean();
      classesList = await Class.find({ schoolId: req.user.schoolId }).lean();
    } else if (req.user.role === 'teacher') {
      classesList = await Class.find({ teacherId: req.user._id }).lean();
      const studentIds = classesList.flatMap(c => c.students);
      students = await User.find({ _id: { $in: studentIds }, role: 'student', schoolId: req.user.schoolId }).lean();
    }

    // Embed classLeader info into student objects to help frontend identify them easily if needed
    // But since the frontend uses classes API to check, we don't strictly need it here, but it's safe.
    res.status(200).json({ success: true, data: students });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.updateStudent = async (req, res) => {
  try {
    const { id } = req.params;
    const { studentId, grNumber, name, email, password, gender, classId, isClassLeader } = req.body;
    
    // Find student
    const student = await User.findOne({ _id: id, role: 'student', schoolId: req.user.schoolId });
    if (!student) {
      return res.status(404).json({ success: false, message: 'Student not found' });
    }

    if (req.user.role === 'teacher') {
      const cls = await Class.findOne({ students: id });
      if (!cls || !cls.teacherId || cls.teacherId.toString() !== req.user._id.toString()) {
        return res.status(403).json({ success: false, message: 'Only the designated Class Teacher can edit students.' });
      }
      if (classId && cls._id.toString() !== classId.toString()) {
        const newCls = await Class.findById(classId);
        if (!newCls || !newCls.teacherId || newCls.teacherId.toString() !== req.user._id.toString()) {
          return res.status(403).json({ success: false, message: 'Only the designated Class Teacher can move students to that class.' });
        }
      }
    }

    // Update user info
    student.studentId = studentId || student.studentId;
    student.grNumber = grNumber || student.grNumber;
    student.name = name || student.name;
    student.email = email || student.email;
    student.gender = gender || student.gender;
    if (password) {
      student.password = password;
    }
    await student.save();

    if (classId) {
      const activeYear = await AcademicYear.findOne({ status: 'active' });
      if (activeYear) {
        const enrollment = await Enrollment.findOne({ studentId: id, academicYearId: activeYear._id });
        if (enrollment && enrollment.classId.toString() !== classId) {
          const updateOldClass = { $pull: { students: id } };
          const oldClassDoc = await Class.findById(enrollment.classId);
          if (oldClassDoc && oldClassDoc.classLeader && oldClassDoc.classLeader.toString() === id.toString()) {
            updateOldClass.$unset = { classLeader: 1 };
          }
          await Class.findByIdAndUpdate(enrollment.classId, updateOldClass);
          
          enrollment.classId = classId;
          await enrollment.save();
          await Class.findByIdAndUpdate(classId, { $addToSet: { students: id } });
        }
      }
    }

    // Handle class leader updates
    const currentClassId = classId || (await Class.findOne({ students: id }))?._id;
    if (currentClassId && isClassLeader !== undefined) {
      const clsDoc = await Class.findById(currentClassId);
      if (isClassLeader === true) {
        await Class.findByIdAndUpdate(currentClassId, { $set: { classLeader: id } });
      } else if (isClassLeader === false && clsDoc && clsDoc.classLeader && clsDoc.classLeader.toString() === id.toString()) {
        await Class.findByIdAndUpdate(currentClassId, { $unset: { classLeader: 1 } });
      }
    }
    res.status(200).json({ success: true, message: 'Student updated successfully', data: student });
  } catch (error) {
    if (error.code === 11000) {
      const field = Object.keys(error.keyValue)[0];
      return res.status(400).json({ success: false, message: `An account with that ${field} already exists.` });
    }
    res.status(500).json({ success: false, message: error.message });
  }
};

exports.deleteStudent = async (req, res) => {
  try {
    const { id } = req.params;
    const student = await User.findOne({ _id: id, role: 'student', schoolId: req.user.schoolId });
    if (!student) {
      return res.status(404).json({ success: false, message: 'Student not found' });
    }

    if (req.user.role === 'teacher') {
      const cls = await Class.findOne({ students: id });
      if (!cls || !cls.teacherId || cls.teacherId.toString() !== req.user._id.toString()) {
        return res.status(403).json({ success: false, message: 'Only the designated Class Teacher can delete students.' });
      }
    }

    // If the student was a class leader, remove them
    const cls = await Class.findOne({ students: id });
    if (cls && cls.classLeader && cls.classLeader.toString() === id.toString()) {
      await Class.findByIdAndUpdate(cls._id, { $unset: { classLeader: 1 } });
    }

    // Fully delete for this demo
    await User.findByIdAndDelete(id);

    res.status(200).json({ success: true, message: 'Student deleted successfully' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};
